import random
quote = random.choice ([
    "Love God at all time's inspaite of the life challenging",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Your time is limited, don't waste it living someone else's life.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Do one thing every day that scares you.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Dream big and dare to fail.",
    "It always seems impossible until it's done.",
    "Don't let yesterday take up too much of today.",
    "You are never too old to set another goal or to dream a new dream.",
    "The best way to predict the future is to create it.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "The only way to do great work is to love what you do.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Act as if what you do makes a difference. It does.",
    "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    "In the middle of every difficulty lies opportunity.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "Start where you are. Use what you have. Do what you can.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "The harder the conflict, the greater the triumph.",
    "It does not matter how slowly you go as long as you do not stop.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Be yourself; everyone else is already taken.",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
    "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.",
    "If opportunity doesn't knock, build a door.",
    "The way to get started is to quit talking and begin doing.",
    "Don’t count the days, make the days count.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The only place where success comes before work is in the dictionary.",
    "Life is short, and it is here to be lived.",
    "Success is not in what you have, but who you are.",
    "Aim for the moon. If you miss, you may hit a star.",
    "The secret of getting ahead is getting started."
    "I never dreamed about success, I worked for it." 
    "Strive not to be a success, but rather to be of value.",
    "Opportunities don't happen. You create them.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Your potential is endless.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Believe you can and you're halfway there.",
])
random.shuffle
print(quote)

